homepage:
  pattern: /
  defaults: { _controller: YrchBundle:Category:show }

category_show:
  locales: { en: /category/:id, fr: /categorie/:id }
  defaults: { _controller: YrchBundle:Category:show }
  requirements: { id: "\d+" }
