homepage:
  pattern: /
  defaults: { _controller: YrchBundle:Category:show }

category_show:
  pattern: /category/:id
  defaults: { _controller: YrchBundle:Category:show }
  requirements: { id: "\d+" }
