imports:
  - { resource: security.yml }
  - { resource: user_config.yml }

app.config:
  charset: UTF-8
  error_handler: null
  csrf_secret: xxxxxxxxxx
  validation: { enabled: true, annotations: true }
  templating:
    #assets_version: SomeVersionScheme
  session:
    auto_start: true
    lifetime: 3600
  translator: { fallback: en }

## Twig Configuration
twig.config:
  debug: %kernel.debug%
  strict_variables: %kernel.debug%
  extensions: [twig.extension.text, twig.extension.debug]

## Doctrine Configuration
doctrine.orm:
  auto_generate_proxy_classes: true
  mappings:
    YrchBundle: ~
    DoctrineExtensionsBundle: ~
    UserBundle: ~

## I18nRoutingBundle
i18n_routing.config:
  router: { resource: "%kernel.root_dir%/config/routing.yml" }

## DoctrineExtensionsBundle
doctrine_extensions.config:
  default: ~
