imports:
  - { resource: security.yml }

framework:
  charset: UTF-8
  router: { resource: "%kernel.root_dir%/config/routing.yml" }
  csrf_protection:
    enabled: true
  secret: xxxxxxxxxx
  validation:
    enabled: true
    annotations: true
  templating:
    engines: [twig]
  session:
    auto_start: true
    lifetime: 3600
    name: Yrch
  translator: { fallback: en }

## Twig Configuration
twig:
  debug: %kernel.debug%
  strict_variables: %kernel.debug%
  extensions: [twig.extension.text, twig.extension.debug]

## Doctrine Configuration
doctrine:
  orm:
    auto_generate_proxy_classes: true
    entity_managers:
      default:
        mappings:
          YrchBundle: ~
          StofDoctrineExtensionsBundle: ~
          FOSUserBundle: ~

## I18nRoutingBundle
be_simple_i18n_routing: ~

## StofDoctrineExtensionsBundle
stof_doctrine_extensions:
  orm:
    default: ~

## FOSUserBundle
fos_user:
  db_driver: orm
  firewall_name: main
  class:
    model:
      user: Yrch\YrchBundle\Entity\User
