imports:
  - { resource: config_dev.yml }
  - { resource: user_config.yml }

framework:
  error_handler: false
  test: ~

web_profiler:
  toolbar: false
  intercept_redirects: false

doctrine:
  dbal:
    connections:
      default:
        dbname: yrch_test

swiftmailer:
  disable_delivery: true
