imports:
  - { resource: config_dev.yml }

app.config:
  error_handler: false
  test: ~

webprofiler.config:
  toolbar: false
  intercept_redirects: false

zend.config:
  logger:
    priority: debug

doctrine.dbal:
  dbname: yrch_test
  user: ~
  password: ~
  host: ~

swiftmailer.config:
  delivery_strategy: none
