imports:
  - { resource: config.yml }
  - { resource: user_config.yml }

framework:
  profiler: { only_exceptions: false }
  router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }

web_profiler:
  toolbar: true
  verbose: false
  intercept_redirects: true

monolog:
  handlers:
    main:
      type:  stream

