imports:
  - { resource: config.yml }
  - { resource: user_config.yml }

monolog:
  handlers:
    main:
      type:         fingerscrossed
      action_level: error
      handler:      nested
    nested:
      type:  stream
