imports:
  - { resource: config.yml }
  - { resource: user_config.yml }

framework:
  profiler: { only_exceptions: false }

web_profiler:
  toolbar: true
  intercept_redirects: true

zend:
  logger:
    priority: info
    path: %kernel.logs_dir%/%kernel.environment%.log

twig:
  auto_reload: true

## I18nRoutingBundle
i18n_routing:
  router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }
