imports:
  - { resource: user_config.yml }

app.config:
  charset: UTF-8
  error_handler: null
  csrf_secret: xxxxxxxxxx
  router: { resource: "%kernel.root_dir%/config/routing.yml" }
  validation: { enabled: true, annotations: true }
  templating:
    #assets_version: SomeVersionScheme
  session:
    auto_start: true
    lifetime: 3600

## Twig Configuration
twig.config:

## Doctrine Configuration
doctrine.orm:
  auto_generate_proxy_classes: true

## I18nRoutingBundle
i18n_routing.config:
  router: { resource: "%kernel.root_dir%/config/routing.yml" }

## DoctrineExtensionsBundle
doctrine_extensions.config: ~
