imports:
  - { resource: config.yml }
  - { resource: user_config.yml }

app.config:
  profiler: { only_exceptions: false }

webprofiler.config:
  toolbar: true
  intercept_redirects: true

zend.config:
  logger:
    priority: info
    path: %kernel.logs_dir%/%kernel.environment%.log

twig.config:
  auto_reload: true

## I18nRoutingBundle
i18n_routing.config:
  router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }
