imports:
  - { resource: security.yml }

framework:
  charset: UTF-8
  router: { resource: "%kernel.root_dir%/config/routing.yml" }
  csrf_protection:
    enabled: true
  secret: xxxxxxxxxx
  form: true
  validation:
    enabled: true
    enable_annotations: true
  templating:
    engines: [twig]
  session:
    auto_start: true
    name: Yrch
  translator: { fallback: en }

## Twig Configuration
twig:
  debug: %kernel.debug%
  strict_variables: %kernel.debug%

## Doctrine Configuration
doctrine:
  orm:
    auto_generate_proxy_classes: true
    entity_managers:
      default:
        mappings:
          YrchBundle: ~
          StofDoctrineExtensionsBundle: ~
          FOSUserBundle: ~

## StofDoctrineExtensionsBundle
stof_doctrine_extensions:
  translation_fallback: true
  orm:
    default:
        translatable: true
        timestampable: true
        tree: true

## FOSUserBundle
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Yrch\YrchBundle\Entity\User
