imports:
  - { resource: security.yml }

framework:
  charset: UTF-8
  error_handler: null
  csrf_protection:
    enabled: true
    secret: xxxxxxxxxx
  validation:
    enabled: true
    annotations: true
  templating:
    engines: [twig]
  session:
    auto_start: true
    lifetime: 3600
    name: Yrch
  translator: { fallback: en }

## Twig Configuration
twig:
  debug: %kernel.debug%
  strict_variables: %kernel.debug%
  extensions: [twig.extension.text, twig.extension.debug]

## Doctrine Configuration
doctrine:
  orm:
    auto_generate_proxy_classes: true
    mappings:
      YrchBundle: ~
      StofDoctrineExtensionsBundle: ~
      FOSUserBundle: ~

## I18nRoutingBundle
i18n_routing:
  router: { resource: "%kernel.root_dir%/config/routing.yml" }

## StofDoctrineExtensionsBundle
stof_doctrine_extensions:
  orm:
    default: ~

## FOSUserBundle
fos_user:
  db_driver: orm
  provider_key: fos_user
  class:
    model:
      user: Yrch\YrchBundle\Entity\User
      group: FOS\UserBundle\Entity\DefaultGroup
