yrch:
  resource: YrchBundle/Resources/config/routing/routing.yml

doctrine_user_user:
  resource: DoctrineUserBundle/Resources/config/routing/user.xml
  prefix: /user

doctrine_user_session:
  resource: DoctrineUserBundle/Resources/config/routing/session.xml
  prefix: /session

