yrch:
  resource: "@YrchBundle/Resources/config/routing/routing.yml"

doctrine_user_user:
  resource: "@FOSUserBundle/Resources/config/routing/user.xml"
  prefix: /user

doctrine_user_session:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

