yrch:
  resource: "@YrchBundle/Resources/config/routing/routing.yml"

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /{_locale}/me

fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
  prefix: /{_locale}

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /{_locale}/reset-password

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /{_locale}/register

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /{_locale}
