yrch:
  resource: "@YrchBundle/Resources/config/routing/routing.yml"

fos_user_user:
  resource: "@FOSUserBundle/Resources/config/routing/user.xml"
  prefix: /user

fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
