security:
  providers:
    fos_user:
      id: fos_user.user_manager
  encoders:
    Yrch\YrchBundle\Entity\User: sha512
  firewalls:
    unsecure:
      pattern: ^/(_wdt|_profiler)/
      security: false
    main:
      pattern:      .*
      form-login:
        login_path:     fos_user_security_login
        use_forward:    false
        check_path:     fos_user_security_check
        failure_path:   null
      logout:
        path: fos_user_security_logout
      anonymous:    true
      switch_user:  true
  access_control:
    - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
  role_hierarchy:
    ROLE_MODERATOR:   ROLE_USER
    ROLE_ADMIN:       ROLE_MODERATOR
    ROLE_SUPERADMIN:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
