security.config:
  providers:
    fos_user:
      id: fos_user.user_manager
  firewalls:
    main:
      pattern:      .*
      form-login:
        login_path:     /login
        use_forward:    false
        check_path:     /login-check
        failure_path:   null
      logout:       true
      anonymous:    true
      switch_user:  true
  access_control:
    - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
  role_hierarchy:
    ROLE_MODERATOR:   ROLE_USER
    ROLE_ADMIN:       ROLE_MODERATOR
    ROLE_SUPERADMIN:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
